list_airports = {
    'ATL': 'Hartsfield-Jackson Atlanta International Airport',
    'ORD': "O'Hare International Airport",
    'DFW': 'Dallas/Fort Worth International Airport',
    'DEN': 'Denver International Airport',
    'CLT': 'Charlotte Douglas International Airport',
    'LAX': 'Los Angeles International Airport',
    'IAH': 'George Bush Intercontinental Airport',
    'PHX': 'Phoenix Sky Harbor International Airport',
    'SFO': 'San Francisco International Airport',
    'LGA': 'LaGuardia Airport',
    'LAS': 'McCarran International Airport',
    'MSP': 'Minneapolis-Saint Paul International Airport',
    'DTW': 'Detroit Metropolitan Wayne County Airport',
    'BOS': 'Logan International Airport',
    'SEA': 'Seattle-Tacoma International Airport',
    'MCO': 'Orlando International Airport',
    'DCA': 'Ronald Reagan Washington National Airport',
    'EWR': 'Newark Liberty International Airport',
    'JFK': 'John F. Kennedy International Airport',
    'PHL': 'Philadelphia International Airport',
    'SLC': 'Salt Lake City International Airport',
    'BWI': 'Baltimore/Washington International Thurgood Marshall Airport',
    'FLL': 'Fort Lauderdale–Hollywood International Airport',
    'SAN': 'San Diego International Airport',
    'MIA': 'Miami International Airport',
    'MDW': 'Chicago Midway International Airport',
    'BNA': 'Nashville International Airport',
    'TPA': 'Tampa International Airport',
    'DAL': 'Dallas Love Field Airport',
    'IAD': 'Washington Dulles International Airport',
    'STL': 'St. Louis Lambert International Airport',
    'AUS': 'Austin-Bergstrom International Airport',
    'RDU': 'Raleigh-Durham International Airport',
    'SJC': 'Norman Y. Mineta San Jose International Airport',
    'PDX': 'Portland International Airport',
    'HOU': 'William P. Hobby Airport',
    'MSY': 'Louis Armstrong New Orleans International Airport',
    'MCI': 'Kansas City International Airport',
    'OAK': 'Oakland International Airport',
    'HNL': 'Honolulu International Airport',
    'SMF': 'Sacramento International Airport',
    'PIT': 'Pittsburgh International Airport',
    'CLE': 'Cleveland Hopkins International Airport',
    'IND': 'Indianapolis International Airport',
    'CVG': 'Cincinnati/Northern Kentucky International Airport',
    'CMH': 'John Glenn Columbus International Airport',
    'SAT': 'San Antonio International Airport',
    'SNA': 'John Wayne Airport',
    'JAX': 'Jacksonville International Airport',
    'RSW': 'Southwest Florida International Airport',
    'BUR': 'Hollywood Burbank Airport',
    'MKE': 'General Mitchell International Airport',
    'BDL': 'Bradley International Airport',
    'OGG': 'Kahului Airport',
    'SJU': 'Luis Muñoz Marín International Airport',
    'OMA': 'Eppley Airfield',
    'CHS': 'Charleston International Airport',
    'MEM': 'Memphis International Airport',
    'PBI': 'Palm Beach International Airport',
    'BUF': 'Buffalo Niagara International Airport',
    'RIC': 'Richmond International Airport',
    'ORF': 'Norfolk International Airport',
    'SDF': 'Louisville Muhammad Ali International Airport',
    'OKC': 'Will Rogers World',
    'ABQ': 'Albuquerque International Sunport',
    'ONT': 'Ontario International Airport',
    'RNO': 'Reno-Tahoe International Airport',
    'ANC': 'Ted Stevens Anchorage International Airport',
    'BHM': 'Birmingham-Shuttlesworth International Airport',
    'GRR': 'Gerald R. Ford International Airport',
    'BOI': 'Boise Airport',
    'TUS': 'Tucson International Airport',
    'PVD': 'T. F. Green Airport',
    'TYS': 'McGhee Tyson Airport',
    'SAV': 'Savannah/Hilton Head International Airport',
    'TUL': 'Tulsa International Airport',
    'ELP': 'El Paso International Airport',
    'DSM': 'Des Moines International Airport',
    'GSP': 'Greenville-Spartanburg International Airport',
    'LGB': 'Long Beach Airport',
    'KOA': 'Kona International',
    'GSO': 'Piedmont Triad International Airport (Greensboro, Caroline du Nord, États-Unis)',
    'ROC': 'Greater Rochester International Airport (Rochester, New York, États-Unis)',
    'LIT': 'Bill and Hillary Clinton National Airport (Little Rock, Arkansas, États-Unis)',
    'SYR': 'Syracuse Hancock International Airport (Syracuse, New York, États-Unis)',
    'MSN': 'Dane County Regional Airport (Madison, Wisconsin, États-Unis)',
    'LIH': 'Lihue Airport (Lihue, Hawaï, États-Unis)',
    'XNA': 'Northwest Arkansas Regional Airport (Bentonville, Arkansas, États-Unis)',
    'DAY': 'Dayton International Airport (Dayton, Ohio, États-Unis)',
    'PNS': 'Pensacola International Airport (Pensacola, Floride, États-Unis)',
    'ALB': 'Albany International Airport (Albany, New York, États-Unis)',
    'MYR': 'Myrtle Beach International Airport (Myrtle Beach, Caroline du Sud, États-Unis)',
    'FAT': 'Fresno Yosemite International Airport (Fresno, Californie, États-Unis)',
    'GEG': 'Spokane International Airport (Spokane, Washington, États-Unis)',
    'PSP': 'Palm Springs International Airport (Palm Springs, Californie, États-Unis)',
    'HPN': 'Westchester County Airport (White Plains, New York, États-Unis)',
    'PWM': 'Portland International Jetport (Portland, Maine, États-Unis)',
    'SFB': 'Orlando Sanford International Airport (Sanford, Floride, États-Unis)',
    'ICT': 'Wichita Dwight D. Eisenhower National Airport (Wichita, Kansas, États-Unis)',
    'COS': 'Colorado Springs Airport (Colorado Springs, Colorado, États-Unis)',
    'BTV': 'Burlington International Airport (Burlington, Vermont, États-Unis)',
    'HSV': 'Huntsville International Airport (Huntsville, Alabama, États-Unis)',
    'MAF': 'Midland International Air and Space Port (Midland, Texas, États-Unis)',
    'AVL': 'Asheville Regional Airport (Asheville, Caroline du Nord, États-Unis)',
    'CID': 'The Eastern Iowa Airport (Cedar Rapids, Iowa, États-Unis)',
    'LEX': 'Blue Grass Airport (Lexington, Kentucky, États-Unis)',
    'VPS': 'Destin–Fort Walton Beach Airport (Eglin Air Force Base, Floride, États-Unis)',
    'CHA': 'Chattanooga Metropolitan Airport (Chattanooga, Tennessee, États-Unis)',
    'SGF': 'Springfield-Branson National Airport (Springfield, Missouri, États-Unis)',
    'SRQ': 'Sarasota–Bradenton International Airport (Sarasota, Floride, États-Unis)',
    'JAN': 'Jackson-Medgar Wiley Evers International Airport (Jackson, Mississippi, États-Unis)',
    'MHT': 'Manchester–Boston Regional Airport (Manchester, New Hampshire, États-Unis)',
    'PIE': 'St. Pete–Clearwater International Airport (Clearwater, Floride, États-Unis)',
    'BTR': 'Baton Rouge Metropolitan Airport',
    'CAE': 'Columbia Metropolitan Airport',
    'SBA': 'Santa Barbara Municipal Airport',
    'SHV': 'Shreveport Regional Airport',
    'LBB': 'Lubbock Preston Smith International Airport',
    'FSD': 'Sioux Falls Regional Airport',
    'FWA': 'Fort Wayne International Airport',
    'SBN': 'South Bend International Airport',
    'BZN': 'Bozeman Yellowstone International Airport',
    'ILM': 'Wilmington International Airport',
    'ECP': 'Northwest Florida Beaches International Airport',
    'TLH': 'Tallahassee International Airport',
    'ASE': 'Aspen/Pitkin County Airport',
    'CAK': 'Akron-Canton Airport',
    'MDT': 'Harrisburg International Airport',
    'ITO': 'Hilo International Airport',
    'FAR': 'Hector International Airport',
    'CRP': 'Corpus Christi International Airport',
    'CHO': 'Charlottesville Albemarle Airport',
    'AZA': 'Phoenix-Mesa Gateway Airport',
    'MFE': 'McAllen Miller International Airport',
    'EYW': 'Key West International Airport',
    'ISP': 'Long Island MacArthur Airport',
    'MOB': 'Mobile Regional Airport',
    'PGD': 'Charlotte County Airport',
    'RAP': 'Rapid City Regional Airport',
    'LFT': 'Lafayette Regional Airport',
    'EUG': 'Eugene Regional Airport',
    'SBP': 'San Luis Obispo County Regional Airport',
    'GNV': 'Gainesville Regional Airport',
    'AMA': 'Rick Husband Amarillo International Airport',
    'GRB': 'Austin Straubel International Airport',
    'ABE': 'Lehigh Valley International Airport',
    'FAI': 'Fairbanks International Airport',
    'MLI': 'Quad City International Airport',
    'AGS': 'Augusta Regional Airport',
    "JAC": "Jackson Hole Airport (Wyoming, USA)",
    "PIA": "General Wayne A. Downing Peoria International Airport (Illinois, USA)",
    "TVC": "Cherry Capital Airport (Michigan, USA)",
    "JNU": "Juneau International Airport (Alaska, USA)",
    "GPT": "Gulfport-Biloxi International Airport (Mississippi, USA)",
    "HRL": "Valley International Airport (Texas, USA)",
    "CRW": "Yeager Airport (West Virginia, USA)",
    "MRY": "Monterey Regional Airport (California, USA)",
    "ATW": "Appleton International Airport (Wisconsin, USA)",
    "BIS": "Bismarck Municipal Airport (North Dakota, USA)",
    "BIL": "Billings Logan International Airport (Montana, USA)",
    "EVV": "Evansville Regional Airport (Indiana, USA)",
    "GJT": "Grand Junction Regional Airport (Colorado, USA)",
    "RDM": "Roberts Field (Oregon, USA)",
    "MFR": "Rogue Valley International-Medford Airport (Oregon, USA)",
    "BGR": "Bangor International Airport (Maine, USA)",
    "STT": "Cyril E. King Airport (U.S. Virgin Islands)",
    "MGM": "Montgomery Regional Airport (Alabama, USA)",
    "MSO": "Missoula International Airport (Montana, USA)",
    "FAY": "Fayetteville Regional Airport (North Carolina, USA)",
    "AVP": "Wilkes-Barre/Scranton International Airport (Pennsylvania, USA)",
    "FNT": "Bishop International Airport (Michigan, USA)",
    "GRK": "Killeen-Fort Hood Regional Airport (Texas, USA)",
    "DLH": "Duluth International Airport (Minnesota, USA)",
    "RST": "Rochester International Airport (Minnesota, USA)",
    "DRO": "Durango-La Plata County Airport (Colorado, USA)",
    "DAB": "Daytona Beach International Airport (Florida, USA)",
    "FCA": "Glacier Park International Airport (Montana, USA)",
    "LAN": "Capital Region International Airport (Michigan, USA)",
    "AEX": "Alexandria International Airport (Louisiana, USA)",
    "BMI": "Central Illinois Regional Airport at Bloomington-Normal (Illinois, USA)",
    "ACY": "Atlantic City International Airport (New Jersey, USA)",
    "TTN": "Trenton-Mercer Airport (New Jersey, USA)",
    "PSC": "Tri-Cities Airport (Washington, USA)",
    "TRI": "Tri-Cities Regional Airport (Tennessee, USA)",
    "MLU": "Monroe Regional Airport (Louisiana, USA)",
    "CMI": "University of Illinois Willard Airport (Illinois, USA)",
    "OAJ": "Albert J. Ellis Airport (North Carolina, USA)",
    "ROA": "Roanoke-Blacksburg Regional Airport (Virginia, USA)",
    "STS": "Charles M. Schulz–Sonoma County Airport (California, USA)",
    "BRO": "Brownsville/South Padre Island International Airport (Texas, USA)",
    "LRD": "Laredo International Airport (Texas, USA)",
    "MLB": "Melbourne International Airport (Florida, USA)",
    "CWA": "Central Wisconsin Airport (Wisconsin, USA)",
    "MBS": "MBS International Airport (Michigan, USA)",
    'PHF': 'Newport News/Williamsburg International Airport (Virginia, USA)',
    'BFL': 'Meadows Field Airport (California, USA)',
    'KTN': 'Ketchikan International Airport (Alaska, USA)',
    'HHH': 'Hilton Head Island Airport (South Carolina, USA)',
    'COU': 'Columbia Regional Airport (Missouri, USA)',
    'SGU': 'St. George Regional Airport (Utah, USA)',
    'EWN': 'Coastal Carolina Regional Airport (North Carolina, USA)',
    'MOT': 'Minot International Airport (North Dakota, USA)',
    'BQN': 'Rafael Hernández Airport (Aguadilla Puerto Rico, USA)',
    'ABI': 'Abilene Regional Airport, Abilene, Texas, USA',
    'CLL': 'Easterwood Airport, College Station, Texas, USA',
    'AZO': 'Kalamazoo/Battle Creek International Airport, Kalamazoo, Michigan, USA',
    'LNK': 'Lincoln Airport, Lincoln, Nebraska, USA',
    'LSE': 'La Crosse Regional Airport, La Crosse, Wisconsin, USA',
    'IDA': 'Idaho Falls Regional Airport, Idaho Falls, Idaho, USA',
    'FSM': 'Fort Smith Regional Airport, Fort Smith, Arkansas, USA',
    'GFK': 'Grand Forks International Airport, Grand Forks, North Dakota, USA',
    'TOL': 'Toledo Express Airport, Toledo, Ohio, USA',
    'EGE': 'Eagle County Regional Airport, Vail, Colorado, USA',
    'ACV': 'Arcata-Eureka Airport, Arcata/Eureka, California, USA',
    'FLG': 'Flagstaff Pulliam Airport, Flagstaff, Arizona, USA',
    'MHK': 'Manhattan Regional Airport, Manhattan, Kansas, USA',
    'LCH': 'Lake Charles Regional Airport, Lake Charles, Louisiana, USA',
    'YUM': 'Yuma International Airport, Yuma, Arizona, USA',
    'SJT': 'San Angelo Regional Airport/Mathis Field, San Angelo, Texas, USA',
    'MTJ': 'Montrose Regional Airport, Montrose, Colorado, USA',
    'BLI': 'Bellingham International Airport, Bellingham, Washington, USA',
    'ACT': 'Waco Regional Airport, Waco, Texas, USA',
    'SCE': 'University Park Airport, State College, Pennsylvania, USA',
    'GTF': 'Great Falls International Airport, Great Falls, Montana, USA',
    'SAF': 'Santa Fe Municipal Airport, Santa Fe, New Mexico, USA',
    'SWF': 'Stewart International Airport, Newburgh, New York, USA',
    'SPI': 'Abraham Lincoln Capital Airport, Springfield, Illinois, USA',
    'PAE': 'Snohomish County Airport (Paine Field), Everett, Washington, USA',
    'SUN': 'Friedman Memorial Airport, Hailey, Idaho, USA',
    'TYR': 'Tyler Pounds Regional Airport, Tyler, Texas, USA',
    'ACK': 'Nantucket Memorial Airport, Nantucket, Massachusetts, USA',
    'JLN': 'Joplin Regional Airport, Joplin, Missouri, USA',
    'MQT': 'Sawyer International Airport, Marquette, Michigan, USA',
    'SIT': 'Sitka Rocky Gutierrez Airport, Sitka, Alaska, USA',
    'RDD': 'Redding Municipal Airport, Redding, California, USA',
    'USA': 'Concord Regional Airport, Concord, North Carolina, USA',
    'ROW': 'Roswell International Air Center, Roswell, New Mexico, USA',
    'PBG': 'Plattsburgh International Airport, Plattsburgh, New York, USA',
    'DHN': 'Dothan Regional Airport, Dothan, Alabama, USA',
    'HLN': 'Helena Regional Airport, Helena, Montana, USA',
    'LAW': 'Lawton-Fort Sill Regional Airport, Lawton, Oklahoma, USA',
    'SUX': 'Sioux Gateway Airport/Brigadier General Bud Day Field, Sioux City, Iowa, USA',
    'PAH': 'Barkley Regional Airport, Paducah, Kentucky, USA',
    'CSG': 'Columbus Metropolitan Airport, Columbus, Georgia, USA',
    'SPS': 'Sheppard Air Force Base/Wichita Falls Municipal Airport, Wichita Falls, Texas, USA',
    'TXK': 'Texarkana Regional Airport, Texarkana',
    'HYS': 'Hays Regional Airport, Hays, Kansas, USA',
    'ORH': 'Worcester Regional Airport, Worcester, Massachusetts, USA',
    'ERI': 'Erie International Airport (Pennsylvanie, États-Unis)',
    'TWF': 'Magic Valley Regional Airport (Idaho, États-Unis)',
    'GTR': 'Golden Triangle Regional Airport (Mississippi, États-Unis)',
    'PLN': 'Pellston Regional Airport (Michigan, États-Unis)',
    'LBE': 'Arnold Palmer Regional Airport (Pennsylvanie, États-Unis)',
    'GRI': 'Central Nebraska Regional Airport (Nebraska, États-Unis)',
    'LCK': 'Rickenbacker International Airport (Ohio, États-Unis)',
    'CPR': 'Casper-Natrona County International Airport (Wyoming, États-Unis)',
    'PIH': 'Pocatello Regional Airport (Idaho, États-Unis)',
    'HVN': 'Tweed New Haven Regional Airport (Connecticut, États-Unis)',
    'BLV': 'Scott Air Force Base (Illinois, États-Unis)',
    'DBQ': 'Dubuque Regional Airport (Iowa, États-Unis)',
    'BQK': 'Brunswick Golden Isles Airport (Géorgie, États-Unis)',
    'VLD': 'Valdosta Regional Airport (Géorgie, États-Unis)',
    'SCK': 'Stockton Metropolitan Airport (Californie, États-Unis)',
    'ABY': 'Southwest Georgia Regional Airport (Géorgie, États-Unis)',
    'ITH': 'Ithaca Tompkins Regional Airport (New York, États-Unis)',
    'LWS': 'Lewiston-Nez Perce County Airport (Idaho, États-Unis)',
    'BPT': 'Jack Brooks Regional Airport (Texas, États-Unis)',
    'MEI': 'Key Field Airport (Mississippi, États-Unis)',
    'SCC': 'Deadhorse Airport (Alaska, États-Unis)',
    'JMS': 'Jamestown Regional Airport (Dakota du Nord, États-Unis)',
    'HDN': 'Yampa Valley Airport (Colorado, États-Unis)',
    'CGI': 'Cape Girardeau Regional Airport (Missouri, États-Unis)',
    'BGM': 'Greater Binghamton Airport (New York, États-Unis)',
    'GGG': 'East Texas Regional Airport (Texas, États-Unis)',
    'SLN': 'Salina Regional Airport (Kansas, États-Unis)',
    'PUB': 'Pueblo Memorial Airport (Colorado, États-Unis)',
    'STX': 'Henry E. Rohlsen Airport (Îles Vierges des États-Unis)',
    'SWO': 'Stillwater Regional Airport (Oklahoma, États-Unis)',
    'LYH': 'Lynchburg Regional Airport (Virginie, États-Unis)',
    'IAG': 'Niagara Falls International Airport (New York, États-Unis)',
    'CKB': 'North Central West Virginia Airport (Virginie-Occidentale, États-Unis)',
    'PSE': 'Mercedita Airport (Porto Rico)',
    'RHI': 'Rhinelander-Oneida County Airport (Wisconsin, États-Unis)',
    'GUM': 'Antonio B. Won Pat International Airport (Guam)',
    'BET': 'Bethel Airport (Alaska, États-Unis)',
    'CDC': 'Cedar City Regional Airport (Utah, États-Unis)',
    'HTS': 'Tri-State Airport (Virginie-Occidentale, États-Unis)',
    'GCC': 'Gillette-Campbell County Airport (Wyoming, États-Unis)',
    'RFD': 'Chicago Rockford International Airport (Illinois, États-Unis)',
    'BJI': 'Bemidji Regional Airport (Minnesota, États-Unis)',
    'ABR': 'Aberdeen Regional Airport (Dakota du Sud, États-Unis)',
    'MVY': "Martha's Vineyard Airport (Massachusetts, États-Unis)",
    'PRC': 'Ernest A. Love Field (Arizona, États-Unis)',
    'RKS': 'Rock Springs-Sweetwater County Airport (Wyoming, États-Unis)',
    'PVU': 'Provo Municipal Airport (Utah, États-Unis)',
    'HOB': 'Lea County Regional Airport (Nouveau-Mexique, États-Unis)',
    'GCK': 'Garden City Regional Airport (Kansas, États-Unis)',
    'CMX': 'Houghton County Memorial Airport (Michigan, États-Unis)',
    'BRW': "Wiley Post–Will Rogers Memorial Airport (Alaska, États-Unis)",
    'PIR': 'Pierre Regional Airport (Dakota du Sud, États-Unis)',
    'EAU': 'Chippewa Valley Regional Airport (Wisconsin, États-Unis)',
    'MKG': 'Muskegon County Airport (Michigan, États-Unis)',
    'WRG': 'Wrangell Airport (Alaska, États-Unis)',
    'PSG': 'Petersburg James A Johnson Airport (Alaska, États-Unis)',
    'CDV': "Merle K. (Mudhole) Smith Airport (Alaska, États-Unis)",
    'YAK': 'Yakutat Airport (Alaska, États-Unis)',
    'OME': 'Nome Airport (Alaska, États-Unis)',
    'DRT': 'Del Rio International Airport (Texas, États-Unis)',
    'OTZ': 'Ralph Wien Memorial Airport (Alaska, États-Unis)',
    'PIB': 'Hattiesburg-Laurel Regional Airport (Mississippi, États-Unis)',
    'ALO': 'Waterloo Regional Airport (Iowa, États-Unis)',
    'SHD': 'Shenandoah Valley Regional Airport (Virginie, États-Unis)',
    'ISN': 'Sloulin Field International Airport (Dakota du Nord, États-Unis)',
    'EAR': 'Kearney Regional Airport (Nebraska, États-Unis)',
    'IMT': 'Ford Airport (Michigan, États-Unis)',
    'BTM': 'Bert Mooney Airport (Montana, États-Unis)',
    'CIU': 'Chippewa County International Airport (Michigan, États-Unis)',
    'EKO': 'Elko Regional Airport (Nevada, États-Unis)',
    'LWB': 'Greenbrier Valley Airport (Virginie-Occidentale, États-Unis)',
    'INL': 'Falls International Airport (Minnesota, États-Unis)',
    'ADQ': 'Kodiak Airport (Alaska, États-Unis)',
    'BRD': 'Brainerd Lakes Regional Airport (Minnesota, États-Unis)',
    'UIN': 'Quincy Regional Airport (Illinois, États-Unis)',
    'CNY': 'Canyonlands Field (Utah, États-Unis)',
    'VEL': 'Vernal Regional Airport (Utah, États-Unis)',
    'HIB': 'Range Regional Airport (Minnesota, États-Unis)',
    'LBL': 'Liberal Mid-America Regional Airport (Kansas, États-Unis)',
    'ESC': 'Delta County Airport (Michigan, États-Unis)',
    'BFF': 'Western Nebraska Regional Airport (Alliance, Nebraska, États-Unis)',
    'LAR': 'Laramie Regional Airport (Laramie, Wyoming, États-Unis)',
    'LBF': 'North Platte Regional Airport (North Platte, Nebraska, États-Unis)',
    'APN': 'Alpena County Regional Airport (Alpena, Michigan, États-Unis)',
    'DVL': 'Devils Lake Regional Airport (Devils Lake, Dakota du Nord, États-Unis)',
    'ELM': 'Elmira/Corning Regional Airport (Horseheads, New York, États-Unis)',
    'ATY': 'Watertown Regional Airport (Watertown, Dakota du Sud, États-Unis)',
    'CYS': 'Cheyenne Regional Airport (Cheyenne, Wyoming, États-Unis)',
    'OGS': 'Ogdensburg International Airport (Ogdensburg, New York, États-Unis)',
    'MMH': 'Mammoth Yosemite Airport (Mammoth Lakes, Californie, États-Unis)',
    'SPN': 'Saipan International Airport (Saipan, Îles Mariannes du Nord)',
    'COD': 'Yellowstone Regional Airport (Cody, Wyoming, États-Unis)',
    'PSM': 'Portsmouth International Airport at Pease (Portsmouth, New Hampshire, États-Unis)',
    'OTH': 'Southwest Oregon Regional Airport (North Bend, Oregon, États-Unis)',
    'WYS': 'Yellowstone Airport (West Yellowstone, Montana, États-Unis)',
    'BKG': 'Branson Airport (Branson, Missouri, États-Unis)',
    'ART': 'Watertown International Airport (Watertown, New York, États-Unis)',
    'GUC': 'Gunnison–Crested Butte Regional Airport (Gunnison, Colorado, États-Unis)',
    'HGR': 'Hagerstown Regional Airport (Hagerstown, Maryland, États-Unis)',
    'SMX': 'Santa Maria Public Airport (Santa Maria, Californie, États-Unis)',
    'XWA': 'Williston Basin International Airport (Williston, Dakota du Nord, États-Unis)',
    'BFM': 'Mobile Downtown Airport (Mobile, Alabama, États-Unis)',
    'STC': 'St. Cloud Regional Airport (St. Cloud, Minnesota, États-Unis)',
    'PPG': 'Pago Pago International Airport (Pago Pago, Samoa américaines)',
    'HYA': 'Barnstable Municipal Airport (Hyannis, Massachusetts, États-Unis)',
    'GST': 'Gustavus Airport (Gustavus, Alaska, États-Unis)',
    'DLG': 'Dillingham Airport (Dillingham, Alaska, États-Unis)',
    'OGD': 'Ogden-Hinckley Airport (Ogden, Utah, États-Unis)',
    'ADK': 'Adak Airport (Adak Island, Alaska, États-Unis)',
    'OWB': 'Owensboro-Daviess County Regional Airport (Owensboro, Kentucky, États-Unis)',
    'AKN': 'King Salmon Airport (King Salmon, Alaska, États-Unis)',
    'PGV': 'Pitt-Greenville Airport (Greenville, Caroline du Nord, États-Unis)'
}